/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import practica1.CuerpoCeleste;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author fvelasco
 */
public class Control extends JFrame {

  private CuerpoCeleste universe;
  
  /**
   * Creates new form Control
   */
  public Control(CuerpoCeleste universe) {
    initComponents();
    // Atributos de referencia
    this.universe = universe;
    
    // Atributos de la ventana
    setTitle ("Control Window");
    setLocation (820, 100);
    
    // Se construye y se abre la ventana de visualizacion
    Visualization visualizationWindow = new Visualization (universe.getCanvas(), this, false);
    visualizationWindow.setVisible(true);
    
    
    // Cuando se cierra esta ventana se llama al método encargado del cierre
    addWindowListener(new WindowAdapter() {
      @Override
      public void windowClosing(WindowEvent e) {
        exit (0);
      }
    });
    
    repaint();
  }

  /// El método encargado del cierre de la aplicación es único
  public void exit (int status) {
    System.exit (status);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_exit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jcb_showAxes = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jcb_spotLight = new javax.swing.JCheckBox();
        jcb_directionalLight = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_exit.setMnemonic('X');
        jb_exit.setText("Exit");
        jb_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_exitActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Axes"));

        jcb_showAxes.setSelected(true);
        jcb_showAxes.setText("Show Axes");
        jcb_showAxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_showAxesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcb_showAxes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcb_showAxes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lights"));

        jcb_spotLight.setSelected(true);
        jcb_spotLight.setText("Spot");
        jcb_spotLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_spotLightActionPerformed(evt);
            }
        });

        jcb_directionalLight.setSelected(true);
        jcb_directionalLight.setText("Directional");
        jcb_directionalLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_directionalLightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcb_spotLight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_directionalLight)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_spotLight)
                    .addComponent(jcb_directionalLight))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_exit)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(135, 135, 135)
                .addComponent(jb_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jb_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_exitActionPerformed
    exit(0);
  }//GEN-LAST:event_jb_exitActionPerformed

  private void jcb_showAxesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_showAxesActionPerformed
    // TODO add your handling code here:
    universe.showAxes (jcb_showAxes.isSelected());
  }//GEN-LAST:event_jcb_showAxesActionPerformed

  private void jcb_spotLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_spotLightActionPerformed
    // TODO add your handling code here:
    universe.setLightOnOff (CuerpoCeleste.SPOTLIGHT, jcb_spotLight.isSelected());
  }//GEN-LAST:event_jcb_spotLightActionPerformed

  private void jcb_directionalLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_directionalLightActionPerformed
    // TODO add your handling code here:
    universe.setLightOnOff (CuerpoCeleste.DIRECTIONALLIGHT, jcb_directionalLight.isSelected());
  }//GEN-LAST:event_jcb_directionalLightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jb_exit;
    private javax.swing.JCheckBox jcb_directionalLight;
    private javax.swing.JCheckBox jcb_showAxes;
    private javax.swing.JCheckBox jcb_spotLight;
    // End of variables declaration//GEN-END:variables
}
